"""
RepoGuard — AI Response Parser.

Handles safe JSON extraction and validation from AI-generated text.
Provides basic field cleaning and fallback protection.
"""

import json
import logging
from typing import Optional, Dict, Any, List

logger = logging.getLogger(__name__)

def parse_ai_json_response(raw_text: str) -> Optional[Dict[str, Any]]:
    """Safely parse JSON from raw text, handling potential Markdown fences."""
    if not raw_text:
        return None

    # Strip MD code fences if present: ```json ... ```
    cleaned_text = raw_text.strip()
    if cleaned_text.startswith("```json"):
        cleaned_text = cleaned_text[7:]
    if cleaned_text.startswith("```"):
        cleaned_text = cleaned_text[3:]
    if cleaned_text.endswith("```"):
        cleaned_text = cleaned_text[:-3]
    
    cleaned_text = cleaned_text.strip()

    try:
        data = json.loads(cleaned_text)
        # Ensure it's a dict and has key fields
        if not isinstance(data, dict):
            return None
        return data
    except Exception as exc:
        logger.error(f"Failed to parse AI JSON: {exc}")
        return None

def validate_and_clean_report_data(data: Dict[str, Any]) -> Dict[str, Any]:
    """Ensures expected fields exist or have default values."""
    return {
        "threat_title": data.get("threat_title", "Security Risk Detected"),
        "severity": data.get("severity", "high"),
        "executive_summary": data.get("executive_summary", "No summary provided by AI."),
        "why_it_matters": data.get("why_it_matters", "This issue is considered sensitive."),
        "affected_assets": data.get("affected_assets", []),
        "key_findings": data.get("key_findings", []),
        "recommended_fixes": data.get("recommended_fixes", []),
        "developer_summary": data.get("developer_summary", "Review the security findings."),
        "confidence_note": data.get("confidence_note", "Report generated by graph reasoning.")
    }
