export const styles = {
  root: {
    display: "flex",
    flexDirection: "column",
    minHeight: "calc(100vh - 53px)",
    color: "#f5f2eb",
  },
  topBar: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    padding: "24px 56px",
    borderBottom: "1px solid #252522",
    flexWrap: "wrap",
    gap: "12px",
  },
  topLeft: {
    display: "flex",
    alignItems: "center",
    gap: "20px",
    flexWrap: "wrap",
  },
  sectionLabel: {
    fontFamily: "'Fraunces', serif",
    fontSize: "1.1rem",
    color: "#2d7a4f",
    letterSpacing: "-0.01em",
  },
  graphMeta: {
    fontSize: "0.65rem",
    color: "#4a4a48",
    letterSpacing: "0.08em",
  },
  readyBadge: {
    fontSize: "0.62rem",
    color: "#2d7a4f",
    border: "1px solid #2d7a4f",
    borderRadius: "999px",
    padding: "4px 10px",
    letterSpacing: "0.08em",
    textTransform: "uppercase",
  },
  pathBadge: {
    display: "flex",
    alignItems: "center",
    gap: "12px",
    padding: "8px 16px",
    border: "1px solid #2a2a28",
    borderRadius: "5px",
  },
  pathSev: {
    fontSize: "0.62rem",
    letterSpacing: "0.1em",
    fontWeight: 700,
  },
  pathLabel: {
    fontSize: "0.68rem",
    color: "#6b6860",
  },
  reportBtn: {
    padding: "9px 20px",
    fontFamily: "'DM Mono', monospace",
    fontSize: "0.75rem",
    backgroundColor: "transparent",
    color: "#2d7a4f",
    border: "1px solid #2d7a4f",
    borderRadius: "5px",
    cursor: "pointer",
    letterSpacing: "0.04em",
  },
  canvasWrap: {
    flex: 1,
    position: "relative",
    height: "calc(100vh - 150px)",
    minHeight: "760px",
    overflow: "hidden",
  },
  canvas: {
    width: "100%",
    height: "100%",
    position: "absolute",
    inset: 0,
    background: "radial-gradient(circle at center, #171715 0%, #111110 65%, #0c0c0b 100%)",
  },
  zoomControls: {
    position: "absolute",
    top: "24px",
    right: "24px",
    display: "flex",
    flexDirection: "column",
    gap: "10px",
    zIndex: 5,
  },
  zoomBtn: {
    width: "42px",
    height: "42px",
    borderRadius: "6px",
    border: "1px solid #2d7a4f",
    backgroundColor: "#111110",
    color: "#2d7a4f",
    fontSize: "1.3rem",
    cursor: "pointer",
    fontFamily: "'DM Mono', monospace",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
  },
  empty: {
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    justifyContent: "center",
    height: "100%",
    minHeight: "500px",
    gap: "16px",
  },
  emptyIcon: {
    fontSize: "3rem",
    color: "#2d7a4f",
    opacity: 0.4,
  },
  emptyTitle: {
    fontFamily: "'Fraunces', serif",
    fontSize: "1.6rem",
    color: "#f5f2eb",
    opacity: 0.3,
    margin: 0,
    letterSpacing: "-0.02em",
  },
  emptyText: {
    fontSize: "0.78rem",
    color: "#6b6860",
    margin: 0,
  },
  legend: {
    position: "absolute",
    bottom: "24px",
    left: "24px",
    display: "flex",
    flexWrap: "wrap",
    gap: "10px",
    maxWidth: "520px",
    zIndex: 4,
  },
  legendItem: {
    display: "flex",
    alignItems: "center",
    gap: "6px",
  },
  legendDot: {
    width: "8px",
    height: "8px",
    borderRadius: "50%",
    flexShrink: 0,
  },
  legendLabel: {
    fontSize: "0.6rem",
    color: "#8a857d",
    letterSpacing: "0.06em",
  },
  tooltip: {
    position: "absolute",
    top: "24px",
    right: "86px",
    backgroundColor: "#111110",
    border: "1px solid #2d7a4f",
    borderRadius: "6px",
    padding: "14px 18px",
    display: "flex",
    flexDirection: "column",
    gap: "4px",
    minWidth: "170px",
    zIndex: 4,
  },
  tooltipLabel: {
    fontSize: "0.6rem",
    letterSpacing: "0.12em",
    textTransform: "uppercase",
    color: "#2d7a4f",
  },
  tooltipName: {
    fontSize: "0.88rem",
    color: "#f5f2eb",
    fontWeight: 500,
  },
  tooltipRow: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    fontSize: "0.7rem",
    marginTop: "4px",
  },
  tooltipScore: {
    color: "#6b6860",
  },
  chainBar: {
    padding: "18px 56px",
    borderTop: "1px solid #252522",
    display: "flex",
    alignItems: "flex-start",
    gap: "24px",
    flexWrap: "wrap",
  },
  chainLabel: {
    fontSize: "0.62rem",
    letterSpacing: "0.12em",
    textTransform: "uppercase",
    color: "#2d7a4f",
    flexShrink: 0,
    paddingTop: "3px",
  },
  chain: {
    display: "flex",
    alignItems: "center",
    flexWrap: "wrap",
    gap: "6px",
  },
  chainStep: {
    display: "flex",
    alignItems: "center",
    gap: "6px",
  },
  chainNode: {
    fontSize: "0.7rem",
    padding: "4px 12px",
    border: "1px solid",
    borderRadius: "3px",
    color: "#f5f2eb",
    backgroundColor: "#1a1a18",
  },
  chainArrow: {
    fontSize: "0.75rem",
    color: "#2d7a4f",
  },
};
